<a href="https://colab.research.google.com/github/LaansDole/AIO2023_CODE/blob/main/MCMCTH/Day27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def matrix_subtraction(data_x, data_y):
  x = np.array(data_x)
  y = np.array(data_y)
  return x - y

In [12]:
x = [[5],[6],[7],[8]]
y = [[1],[2],[3],[4]]

print(matrix_subtraction(x, y))

[[4]
 [4]
 [4]
 [4]]


In [4]:
def matrix_transpose(matrix):
  m = np.array(matrix)
  return m.T

In [5]:
matrix = [[1,2], [3,4]]
print(matrix_transpose(matrix))

[[1 3]
 [2 4]]


In [15]:
def matrix_multiplication(matrix_x, matrix_y):
  x = np.array(matrix_x)
  y = np.array(matrix_y)
  return np.dot(x, y)

In [16]:
print(matrix_multiplication([1,2,3],2))

[2 4 6]


In [17]:
print(matrix_multiplication([1,2], [[2],[3]]))

[8]
