<a href="https://colab.research.google.com/github/LaansDole/AIO2023_CODE/blob/main/MCMCTH/Day29_numpy_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.version.version)

1.22.4


In [5]:
data_1D = np.arange(4,10)
print(data_1D)

[4 5 6 7 8 9]


In [6]:
data_3D_1 = np.ones((3,3), dtype = int)
print(data_3D_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
data_3D_2 = np.ones((3,3)) > 0
print(data_3D_2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
data_3D_3 = np.ones((3,3), dtype = bool)
print(data_3D_3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# Conditions
data_4 = np.arange(10)
data_4_w1 = [d for d in data_4 if (d%2 == 1)]
print(np.array(data_4_w1))

data_4_w2  = data_4[data_4%2==1]
print(data_4_w2)

[1 3 5 7 9]
[1 3 5 7 9]


In [18]:
# Replace odd numbers by -1
out = np.where(data_4%2 == 1, -1, data_4)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
# Reshape

data_5 = np.arange(10).reshape(2,5)
print(data_5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
data_6 = np.repeat(7,10).reshape(2,-1)
print(data_6)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [37]:
out1 = np.concatenate([data_5, data_6], axis = 0)
print(out1)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [32]:
out2 = np.vstack([data_5, data_6])
print(out2)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [40]:
out3 = np.hstack([data_5, data_6])
print(out3)

[[0 1 2 3 4 7 7 7 7 7]
 [5 6 7 8 9 7 7 7 7 7]]


In [43]:
# Return common elements
out4 = np.intersect1d(np.arange(10), np.repeat(7,10))
print(out4)

[7]


In [50]:
# Return positions of common elements
data1 = np.array([1,2,3,4,5,6])
data2 = np.array([1,1,1,6,6,6])

# compare the two arrays
comp = (data1==data2).nonzero()
print(comp)

(array([0, 5]),)
